import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      colorScheme: colorScheme,
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            side: BorderSide(
              color: colorScheme.primary,
              width: 2,
            ),
            borderRadius: BorderRadius.circular(
              6,
            ),
          ),
        ),
      ),
      textTheme: TextTheme(
        bodyMedium: TextStyle(
          color: colorScheme.primary,
          fontSize: getFontSize(
            15,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
        ),
        labelLarge: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: getFontSize(
            13,
          ),
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w900,
        ),
        displaySmall: TextStyle(
          color: colorScheme.primary,
          fontSize: getFontSize(
            36,
          ),
          fontFamily: 'Comfortaa',
          fontWeight: FontWeight.w400,
        ),
      ),
      visualDensity: VisualDensity.standard,
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    onPrimary: Color(0XFFFFFFFF),
    shadow: Color(0XFFFFFFFF),
    onPrimaryContainer: Color(0XFF000000),
    onTertiary: Color(0XFF000000),
    scrim: Color(0XFFFFFFFF),
    primaryContainer: Color(0XFFFFFFFF),
    tertiaryContainer: Color(0XFF000000),
    secondaryContainer: Color(0XFF000000),
    error: Color(0XFFFFFFFF),
    onErrorContainer: Color(0XFFFFFFFF),
    outline: Color(0XFFFFFFFF),
    onSurfaceVariant: Color(0XFFFFFFFF),
    onBackground: Color(0XFF000000),
    outlineVariant: Color(0XFFFFFFFF),
    errorContainer: Color(0XFF000000),
    onSurface: Color(0XFF000000),
    onError: Color(0XFF000000),
    surface: Color(0XFFFFFFFF),
    onInverseSurface: Color(0XFF000000),
    onSecondaryContainer: Color(0XFFFFFFFF),
    tertiary: Color(0XFFFFFFFF),
    surfaceTint: Color(0XFFFFFFFF),
    onTertiaryContainer: Color(0XFFFFFFFF),
    surfaceVariant: Color(0XFF000000),
    inversePrimary: Color(0XFFFFFFFF),
    secondary: Color(0XFFFFFFFF),
    inverseSurface: Color(0XFFFFFFFF),
    background: Color(0XFFFFFFFF),
    onSecondary: Color(0XFF000000),
    primary: Color(0XFF000000),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  Color get primaryVariant => Color(0XFFFFFFFF);
  Color get secondaryVariant => Color(0XFF000000);
  Color get blueGray400 => Color(0XFF888888);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
